apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "httpproducer.fullname" . }}
  labels:
    {{- include "httpproducer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "httpproducer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "httpproducer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: API_BASEADDRESS
            value: "{{ .Values.apiBaseUri }}"
          - name: DELAY
            value: "{{ .Values.delay }}"
          - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
            value: "120"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}