apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podidverification.fullname" . }}
  labels:
    {{- include "podidverification.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "podidverification.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "podidverification.fullname" . }}
        aadpodidbinding: "{{ .Values.aksClusterName }}-podid"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --subscriptionid={{ .Values.subscriptionId }}
            - --clientid={{ .Values.clientId }}
            - --resourcegroup={{ .Values.resourceGroup }}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}