apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: primary-kvlt-secrets
spec:
  provider: azure
  secretObjects:
  - secretName: api-silo-secrets
    type: Opaque
    data: 
    - objectName: orleans-stg-conn-string
      key: orleans-stg-conn-string
    - objectName: api-auth-rule
      key: api-auth-rule

  - secretName: processor-silo-secrets
    type: Opaque
    data: 
    - objectName: orleans-stg-conn-string
      key: orleans-stg-conn-string
    - objectName: cosmos-account-key
      key: cosmos-account-key
    - objectName: processor-auth-rule
      key: processor-auth-rule

  parameters:
    usePodIdentity: "true"
    keyvaultName: "{{ .Values.keyVaultName }}"
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: "OrleansStorageAccountConnectionString{{ .Values.regionName | upper }}"
          objectType: secret
          objectAlias: orleans-stg-conn-string
          objectVersion: ""
        - |
          objectName: "ApiAuthRule{{ .Values.regionName | upper }}"
          objectType: secret
          objectAlias: api-auth-rule
          objectVersion: ""
        - |
          objectName: "CosmosDbAccountKey"
          objectType: secret
          objectAlias: cosmos-account-key
          objectVersion: ""
        - |
          objectName: "ProcessorAuthRule{{ .Values.regionName | upper }}"
          objectType: secret
          objectAlias: processor-auth-rule
          objectVersion: ""
    tenantId: "{{ .Values.tenantId }}"