# Default values for apisilohost.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: true
  minReplicas: 4
  maxReplicas: 32
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {
  agentpool: api
}