# Default values for secretsvalidation.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: k8s.gcr.io/e2e-test-images/busybox
  pullPolicy: IfNotPresent
  tag: "1.29"

nodeSelector: {}