apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "processorsilohost.fullname" . }}
  labels:
    {{- include "processorsilohost.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "processorsilohost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        aadpodidbinding: "{{ .Values.aksClusterName }}-podid"
        {{- include "processorsilohost.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: siloport
              containerPort: 11111
              protocol: TCP
            - name: gatewayport
              containerPort: 30000
              protocol: TCP
          volumeMounts:
          - name: kvlt-secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true
          env:
          - name: INSTRUMENTATION_KEY
            valueFrom:
              secretKeyRef:
                name: api-silo-secrets
                key: ai-instrumentation-key
          - name: COSMOSDB_ACCOUNTENDPOINT
            valueFrom:
              secretKeyRef:
                name: processor-silo-secrets
                key: cosmos-account-endpoint
          - name: COSMOSDB_ACCOUNTKEY
            valueFrom:
              secretKeyRef:
                name: processor-silo-secrets
                key: cosmos-account-key
          - name: COSMOSDB_DATABASE
            value: sensors
          - name: COSMOSDB_GRAIN_COLLECTION
            value: grains
          - name: STORAGEACCOUNT_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: processor-silo-secrets
                key: orleans-stg-conn-string
          - name: EVENTHUB_CONNECTIONSTRING
            valueFrom:
              secretKeyRef:
                name: processor-silo-secrets
                key: processor-auth-rule
          - name: EVENTHUB_PATH
            value: telemetry
          - name: EVENTHUB_CONSUMERGROUP
            value: processor-silo
          # Configure settings to let Orleans know which cluster it belongs to
          # and which pod it is running in
          - name: ORLEANS_SERVICE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/serviceId']
          - name: ORLEANS_CLUSTER_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['orleans/clusterId']
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
            value: "120"
      terminationGracePeriodSeconds: 180
      volumes:
        - name: kvlt-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: primary-kvlt-secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1